[package]
name = "clapgrep-core"
version = "1.0.0"
edition = "2021"

[dependencies]
regex = "1.11"
grep = "0.3"
ignore = "0.4"
flume = "0.11.1"

# for office support
dotext = "0.1.1"

# for pdf support
pdf-extract = "0.8.0"
euclid = "0.20.14"     # must match pdf-extract::euclid version
